# Generated by Django 3.2.5 on 2021-08-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('working_status', models.CharField(choices=[('freelance available', 'Freelance Available'), ('freelance not available', 'Freelance not available')], max_length=100)),
            ],
        ),
    ]
