# Generated by Django 3.2.5 on 2021-07-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('profile_name', models.CharField(max_length=20)),
                ('profile_bio', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('github', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('wallpaper_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slide_bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio1', models.CharField(blank=True, max_length=50, null=True)),
                ('bio2', models.CharField(blank=True, max_length=50, null=True)),
                ('bio3', models.CharField(blank=True, max_length=50, null=True)),
                ('bio4', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
