# Generated by Django 3.2.5 on 2021-08-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('age', models.CharField(blank=True, max_length=5, null=True)),
                ('residence', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(default='clients/client-1.png', upload_to='clients')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='testimonial/testimonial-1.jpg', upload_to='testimonial')),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('client_name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='What_i_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='slide_bio',
            old_name='bio1',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='slide_bio',
            name='bio2',
        ),
        migrations.RemoveField(
            model_name='slide_bio',
            name='bio3',
        ),
        migrations.RemoveField(
            model_name='slide_bio',
            name='bio4',
        ),
        migrations.AddField(
            model_name='home',
            name='add_cv',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='footer_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='wallpaper_last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='portfolio/portfolio.jpg', upload_to='portfolio')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('client_name', models.CharField(max_length=50)),
                ('company_url', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.category')),
                ('tech', models.ManyToManyField(to='index.Technology')),
            ],
        ),
    ]
