# Generated by Django 3.2.5 on 2021-07-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='footer_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='wallpaper_last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
