# Generated by Django 3.2.5 on 2021-07-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210801_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide_bio',
            old_name='bio1',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='slide_bio',
            name='bio2',
        ),
        migrations.RemoveField(
            model_name='slide_bio',
            name='bio3',
        ),
        migrations.RemoveField(
            model_name='slide_bio',
            name='bio4',
        ),
    ]
