# Generated by Django 3.2.5 on 2021-08-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210801_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
