# Generated by Django 3.2.5 on 2021-08-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='portfolio/portfolio.jpg', upload_to='portfolio')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('client_name', models.CharField(max_length=50)),
                ('company_url', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.category')),
                ('tech', models.ManyToManyField(to='index.Technology')),
            ],
        ),
    ]
