# Generated by Django 3.2.5 on 2021-08-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_about_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_me',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='about_me',
            old_name='Residence',
            new_name='residence',
        ),
        migrations.RemoveField(
            model_name='about_me',
            name='Description',
        ),
        migrations.AddField(
            model_name='about_me',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
