# Generated by Django 3.2.5 on 2021-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='hi',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
