# Generated by Django 3.2.5 on 2021-08-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210801_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='What_i_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about_me',
            name='residence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
