# Generated by Django 3.2.5 on 2021-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210801_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='testimonial/testimonial-1,jpg', upload_to='testimonial')),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('client_name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
    ]
