# Generated by Django 3.2.5 on 2021-08-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210802_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='hi',
        ),
    ]
