# Generated by Django 3.2.5 on 2021-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210801_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='add_cv',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
