# Generated by Django 3.2.5 on 2021-08-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210802_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_me',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='What_i_do',
        ),
    ]
